### ISSUE TITLE
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

### ISSUE THREAD

**Issue by coufin** [hmorimitsu/ptlflow#34] opened 2022-07-15 11:42 UTC

**Comment by hmorimitsu** [comment] 2022-07-18 02:51
Hi, could you tell me which version of pytorch and pytorch-lightning you are using?

**Comment by coufin** [comment] 2022-07-19 00:25
Another problem is when I try to train this
python3 train.py pwcnet --train_dataset kitti-training --val_dataset none --train_batch_size 1 --train_crop_size 512 128 --max_epochs 100 --lr 1e-3
the error is 
/.local/lib/python3.10/site-packages/ptlflow/data/datasets.py", line 911, in __init__
    assert len(img1_paths) == len(flow_paths), f'{len(img1_paths)} vs {len(flow_paths)}'
AssertionError: 0 vs 200

**Comment by hmorimitsu** [comment] 2022-07-19 00:50
> Another problem is when I try to train this python3 train.py pwcnet --train_dataset kitti-training --val_dataset none --train_batch_size 1 --train_crop_size 512 128 --max_epochs 100 --lr 1e-3 the error is /.local/lib/python3.10/site-packages/ptlflow/data/datasets.py", line 911, in **init** assert len(img1_paths) == len(flow_paths), f'{len(img1_paths)} vs {len(flow_paths)}' AssertionError: 0 vs 200

This means that the images are not found. You should check if the KITTI images are in the correct directories. For KITTI 2012, they should be at: `<kitti_2012_root_dir>/training/colored_0/`, and for KITTI 2015 it's: `<kitti_2015_root_dir>/training/image_2/`. The image names should also follow the KITTI standard, which is `*_10.png` and `*_11.png`.

**Comment by hmorimitsu** [comment] 2022-07-19 01:53
> /python3.8/site-packages/ptlflow/utils/callbacks/logger.py", line 411, in _compute_max_range max_range = int(limit_batches * dataloader_length) - 1 TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

Thank you for reporting this problem.

It was caused by a change in the default value in the arguments of pytorch-lightning. It is now fixed in the `main` branch.

To fix your code, please update to the latest version of this repo or downgrade your pytorch-lightning to 1.5.

**Comment by coufin** [comment] 2022-07-19 14:01
I want to know how to solve this error
/.local/lib/python3.8/site-packages/ptlflow/models/base_model/base_model.py", line 337, in configure_optimizers
    assert self.loss_fn is not None, f'Model {self.__class__.__name__} cannot be trained. It does not have loss function.'
AssertionError: Model LiteFlowNet cannot be trained. It does not have loss function.

**Comment by hmorimitsu** [comment] 2022-07-19 15:19
This is currently a limitation of the code. Not all models can be trained.

In this case, this model does not have a loss function yet. This is because the original code was not in PyTorch and I did not convert the training part to my library. Making sure that the training is correct takes a long time, so I only added training when the original code also provided it in PyTorch.

**Comment by coufin** [comment] 2022-07-20 01:05
And how to solve this
/.local/lib/python3.10/site-packages/torch/utils/data/sampler.py", line 107, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0

**Comment by coufin** [comment] 2022-07-20 22:51
It is working. Thank you

**Comment by coufin** [comment] 2022-07-22 14:11
How can I calculate F1-score for the model?

**Comment by hmorimitsu** [comment] 2022-07-23 11:23
F1 is returned as a metric when you use a model that predicts either: confidence, occlusion, or motion boundaries.

You can see the available metrics at: https://github.com/hmorimitsu/ptlflow/blob/main/ptlflow/utils/flow_metrics.py

**Comment by coufin** [comment] 2022-07-25 13:52
How can I see the metrics after training a model?

**Comment by hmorimitsu** [comment] 2022-07-26 01:23
The metrics are logged by pytorch-lightning, which by default is using tensorboard for visualization.

If you want to see them in another way, you should change the base_model and maybe the train scripts.

**Comment by coufin** [comment] 2022-07-28 23:42
Hello, I want to know what do epe and px1, px3 stand for in results.

**Comment by hmorimitsu** [comment] 2022-07-29 01:45
EPE (end-point-error): the average Euclidean distance between the prediction and the groundtruth
px1, px3: percentage of predictions within 1 (or 3) pixels away from the groundtruth

**Comment by coufin** [comment] 2022-07-29 01:52
In Tensorboard I only see epe, outlier, but no F1, where can I see it?

**Comment by hmorimitsu** [comment] 2022-07-29 17:55
Are you using a model and a dataset that has confidence, occlusion, or motion boundaries?

**Comment by coufin** [comment] 2022-07-30 12:12
I use the model: PWCNet
and dataset is KITTI-2012

**Comment by hmorimitsu** [comment] 2022-07-30 13:31
Do you really mean F1 or FL (the metric from KITTI 2015)?

If FL, then it is the same as the outlier metric.

If you really want F1, then it is not available for PWCNet, as this model does not output confidence, occlusion, or motion boundaries predictions.

**Comment by coufin** [comment] 2022-07-30 13:50
OK, but models raft and Flownets also can't see F1. Are they also not available?
And what is FL mean for models?

**Comment by hmorimitsu** [comment] 2022-07-30 13:58
Very few models have predictions compatible with F1. At the moment, there is not any list of models which support it, the only way is to look at their code or read the respective papers.

For FL, I recommend you check the outlier results for the KITTI 2015 dataset.

**Comment by coufin** [comment] 2022-07-30 14:00
OK tahnk you.

**Comment by coufin** [comment] 2022-08-08 14:42
when run craft I have this error
RuntimeError: CUDA out of memory. Tried to allocate 286.00 MiB (GPU 0; 7.79 GiB total capacity; 6.15 GiB already allocated; 69.25 MiB free; 6.29 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.

**Comment by coufin** [comment] 2022-09-06 13:34
I want to know where can I see the metrics of the test of these model?
I can only see metrics like epe, px1 of train in tensorboard

**Comment by coufin** [comment] 2022-09-07 15:31
When I train model dicl: The error is this
RuntimeError: The expanded size of the tensor (1) must match the existing size (0) at non-singleton dimension 3.  Target sizes: [1, 32, 5, 1].  Tensor sizes: [32, 5, 0]

**Comment by hmorimitsu** [comment] 2022-09-08 04:53
> I want to know where can I see the metrics of the test of these model?
> I can only see metrics like epe, px1 of train in tensorboard

By default, validation is run at the end of every epoch of training. So you should see the validation metrics as well.

Did you configure the `datasets.yml` file to point to the validation datasets?

**Comment by hmorimitsu** [comment] 2022-09-08 04:54
> When I train model dicl: The error is this
> RuntimeError: The expanded size of the tensor (1) must match the existing size (0) at non-singleton dimension 3.  Target sizes: [1, 32, 5, 1].  Tensor sizes: [32, 5, 0]

Thanks for reporting. I'll take a look later to see what's wrong.

**Comment by coufin** [comment] 2022-09-27 13:53
Can you tell me the difference between epe and loss?

**Comment by hmorimitsu** [comment] 2022-09-29 13:52
EPE is just a value (the Euclidean distance), while the loss is the signal that drives the training. EPE could be used as the loss signal, but so could other values as well.

**Comment by coufin** [comment] 2022-10-17 13:20
I want to know what is the signal of loss in the models, and why if epe used as loss signal why they are different?

**Comment by coufin** [comment] 2022-11-08 16:25
If I want the x-axis change to epoch from batch in tensorboard, What should I do?
file:///home/hu/Documents/topic/data/kitti%20batch=2/epe_epoch.png

**Comment by coufin** [comment] 2022-11-08 16:26
If I want the x-axis change to epoch from batch in tensorboard, What should I do?

**Comment by coufin** [comment] 2022-11-08 16:29
![epe_epoch](https://user-images.githubusercontent.com/109352531/200621208-e21e1876-7abe-4ac6-8078-1b56b7c4a8f4.png)

**Closed** 2022-11-28 08:49 UTC
